# Generated by Django 3.1 on 2020-08-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('preparation_time', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField()),
                ('vegetarian', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=120)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField()),
                ('dishes', models.ManyToManyField(to='menuAPI.Dish')),
            ],
        ),
    ]
