# Generated by Django 3.1 on 2020-09-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
