# Generated by Django 3.1 on 2020-09-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuAPI', '0002_auto_20200902_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucard',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menucard',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
