# Generated by Django 3.1 on 2020-09-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuAPI', '0003_auto_20200903_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucard',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='menuAPI.Dish'),
        ),
    ]
